version: '3.8'

# Development environment with hot reload and debugging
services:
  mysql-dev:
    image: mysql:8.0
    container_name: webcrawler-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_DATABASE: webcrawler_dev
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - webcrawler-dev
    command: --default-authentication-plugin=mysql_native_password

  # Redis for development (session storage, caching)
  redis-dev:
    image: redis:7-alpine
    container_name: webcrawler-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"  # Different port
    volumes:
      - redis_dev_data:/data
    networks:
      - webcrawler-dev

  # MailHog for email testing (if needed)
  mailhog:
    image: mailhog/mailhog
    container_name: webcrawler-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - webcrawler-dev

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webcrawler-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-dev
      PMA_PORT: 3306
      PMA_USER: devuser
      PMA_PASSWORD: devpass
    ports:
      - "8081:80"
    depends_on:
      - mysql-dev
    networks:
      - webcrawler-dev

networks:
  webcrawler-dev:
    driver: bridge

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local
