# Prometheus configuration for monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor the Go backend application
  - job_name: 'webcrawler-api'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # Monitor MySQL database
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:9104']
    scrape_interval: 10s

  # Monitor Redis if enabled
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

  # Monitor Nginx frontend
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /metrics
    scrape_interval: 15s
